name = "MagFieldLFT"
uuid = "4d626724-46bd-4bad-9021-ec4aea92086c"
authors = ["Lucas Lang <lucas.lang@campus.tu-berlin.de>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OutputParser = "554c801b-3592-4aac-babc-bdcf42564d4b"
Permutations = "2ae35dd2-176d-5d53-8349-f30d82d94d4f"
