name = "MagFieldLFT"
uuid = "4d626724-46bd-4bad-9021-ec4aea92086c"
authors = ["Lucas Lang <lucas.lang@campus.tu-berlin.de>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
